<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>Asser.Sc4Buddy.Server.Api</RootNamespace>
		<AssemblyName>Asser.Sc4Buddy.Server.Api</AssemblyName>
		<SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
		<RestorePackages>true</RestorePackages>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SimCity4.ModManager\SimCity4.ModManager.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="RestSharp" Version="111.4.1" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.4.0" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
		<PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.4" />
	</ItemGroup>
</Project>