<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Nihei.SC4Buddy</RootNamespace>
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <SolutionDir Condition="$(SolutionDir) == '' Or $(SolutionDir) == '*Undefined*'">..\</SolutionDir>
    <RestorePackages>true</RestorePackages>
    <PublishUrl>ftp://web17.gigahost.dk/www/static.nihei.dk/downloads/sc4buddy/</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>true</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <InstallUrl>http://static.nihei.dk/downloads/sc4buddy/</InstallUrl>
    <SupportUrl>http://community.simtropolis.com/topic/58814-the-simcity-4-buddy-project/</SupportUrl>
    <ProductName>SimCity 4 Buddy</ProductName>
    <PublisherName>IrradiatedGames</PublisherName>
    <MinimumRequiredVersion>1.0.0.0</MinimumRequiredVersion>
    <CreateWebPageOnPublish>true</CreateWebPageOnPublish>
    <WebPage>publish.htm</WebPage>
    <ApplicationRevision>22</ApplicationRevision>
    <ApplicationVersion>1.1.0.%2a</ApplicationVersion>
    <UseApplicationTrust>true</UseApplicationTrust>
    <CreateDesktopShortcut>true</CreateDesktopShortcut>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>none</DebugType>
    <DefineConstants>
    </DefineConstants>
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject>Nihei.SC4Buddy.Program</StartupObject>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>78CE61E3097A66B3CA078435277EBEFC02523562</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>SC4Buddy_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>false</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>false</SignManifests>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <TargetZone>LocalIntranet</TargetZone>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Application\Control\ISettingsController.cs">
      <DependentUpon>SettingsController.cs</DependentUpon>
    </Compile>
    <Compile Update="Plugins\Control\IPluginsController.cs">
      <DependentUpon>PluginsController.cs</DependentUpon>
    </Compile>
    <Compile Update="DataAccess\IEntities.cs">
      <DependentUpon>Entities.cs</DependentUpon>
    </Compile>
    <Compile Update="UserFolders\Control\IUserFolderController.cs">
      <DependentUpon>UserFolderController.cs</DependentUpon>
    </Compile>
    <Compile Update="UserFolders\Control\IUserFoldersController.cs">
      <DependentUpon>UserFoldersController.cs</DependentUpon>
    </Compile>
    <Compile Update="Plugins\Services\IDependencyChecker.cs">
      <DependentUpon>DependencyChecker.cs</DependentUpon>
    </Compile>
    <Compile Update="Plugins\Services\IPluginMatcher.cs">
      <DependentUpon>PluginMatcher.cs</DependentUpon>
    </Compile>
    <Compile Update="UserFolders\DataAccess\IUserFolderDataAccess.cs">
      <DependentUpon>UserFolderDataAccess.cs</DependentUpon>
    </Compile>
    <Compile Update="UserFolders\DataAccess\IUserFoldersDataAccess.cs">
      <DependentUpon>UserFoldersDataAccess.cs</DependentUpon>
    </Compile>
    <Compile Update="Utils\IJsonFileWriter.cs">
      <DependentUpon>JsonFileWriter.cs</DependentUpon>
    </Compile>
    <Compile Update="View\Elements\UserFolderToolStripMenuItem.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\error.png" />
    <EmbeddedResource Include="Resources\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\TreeViewIcons\TreeView_Folder.gif" />
    <EmbeddedResource Include="Resources\TreeViewIcons\TreeView_FolderOpen.gif" />
    <EmbeddedResource Include="Resources\TreeViewIcons\TreeView_Leaf.gif" />
    <EmbeddedResource Include="Resources\zoom.png" />
    <Content Include="Resources\Wallpapers\13.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\12.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\11.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\1.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\10.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\2.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\3.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\4.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\5.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\6.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\7.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\8.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Wallpapers\9.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.5">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.5 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.4.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BuddyServerApiClient\BuddyServerApiClient.csproj" />
    <ProjectReference Include="..\NiheiCommon\NiheiCommon.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ByteSize" Version="2.1.2" />
    <PackageReference Include="log4net" Version="2.0.17" />
    <PackageReference Include="morelinq" Version="4.3.0" />
    <PackageReference Include="RestSharp" Version="111.4.1" />
    <PackageReference Include="SharpCompress" Version="0.37.2" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.1" />
  </ItemGroup>
</Project>