<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<OutputType>WinExe</OutputType>
		<IsWebBootstrapper>true</IsWebBootstrapper>
		<MapFileExtensions>true</MapFileExtensions>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	</PropertyGroup>
	
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<UseVSHostingProcess>false</UseVSHostingProcess>
	</PropertyGroup>
	
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>none</DebugType>
		<GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
	</PropertyGroup>
	
	<PropertyGroup>
		<StartupObject>SimCity4.ModManager.App.Program</StartupObject>
		<GenerateManifests>false</GenerateManifests>
		<SignManifests>false</SignManifests>
		<ApplicationIcon>Resources\icon.ico</ApplicationIcon>
		<ApplicationManifest>Properties\app.manifest</ApplicationManifest>
		<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\error.png" />
		<EmbeddedResource Include="Resources\icon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Resources\logo.png">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</EmbeddedResource>
		<EmbeddedResource Include="Resources\TreeViewIcons\TreeView_Folder.gif" />
		<EmbeddedResource Include="Resources\TreeViewIcons\TreeView_FolderOpen.gif" />
		<EmbeddedResource Include="Resources\TreeViewIcons\TreeView_Leaf.gif" />
		<EmbeddedResource Include="Resources\zoom.png" />
		<Content Include="Resources\Wallpapers\13.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\12.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\11.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\1.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\10.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\2.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\3.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\4.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\5.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\6.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\7.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\8.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Resources\Wallpapers\9.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.4.0" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
		<PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.4" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
		<PackageReference Include="ByteSize" Version="2.1.2" />
		<PackageReference Include="log4net" Version="2.0.17" />
		<PackageReference Include="morelinq" Version="4.3.0" />
		<PackageReference Include="RestSharp" Version="111.4.1" />
		<PackageReference Include="SharpCompress" Version="0.37.2" />
		<PackageReference Include="ZstdSharp.Port" Version="0.8.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BuddyServerApiClient\BuddyServerApiClient.csproj" />
	</ItemGroup>
</Project>