//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimCity4.ModManager.App.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimCity4.ModManager.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm installation of plugins.
        /// </summary>
        internal static string ConfirmInstallationOfPlugins {
            get {
                return ResourceManager.GetString("ConfirmInstallationOfPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature disabled.
        /// </summary>
        internal static string Feature_disabled {
            get {
                return ResourceManager.GetString("Feature_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to group files automatically..
        /// </summary>
        internal static string FolderScannerForm_AutoGroupBackgroundWorkerDoWork_Attempting_to_group_files_automatically_ {
            get {
                return ResourceManager.GetString("FolderScannerForm_AutoGroupBackgroundWorkerDoWork_Attempting_to_group_files_autom" +
                        "atically_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} plugin(s)..
        /// </summary>
        internal static string FolderScannerForm_AutoGroupBackgroundWorkerRunWorkerCompleted_Found__0__plugin_s__ {
            get {
                return ResourceManager.GetString("FolderScannerForm_AutoGroupBackgroundWorkerRunWorkerCompleted_Found__0__plugin_s_" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of auto grouping.
        /// </summary>
        internal static string FolderScannerForm_AutoGroupBackgroundWorkerRunWorkerCompleted_Result_of_auto_grouping {
            get {
                return ResourceManager.GetString("FolderScannerForm_AutoGroupBackgroundWorkerRunWorkerCompleted_Result_of_auto_grou" +
                        "ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the auto grouping of plugins?.
        /// </summary>
        internal static string FolderScannerForm_FolderScannerFormFormClosing_Do_you_want_to_cancel_the_auto_grouping_of_plugins_ {
            get {
                return ResourceManager.GetString("FolderScannerForm_FolderScannerFormFormClosing_Do_you_want_to_cancel_the_auto_gro" +
                        "uping_of_plugins_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel the scanning for new files?.
        /// </summary>
        internal static string FolderScannerForm_FolderScannerFormFormClosing_Do_you_want_to_cancel_the_scanning_for_new_files_ {
            get {
                return ResourceManager.GetString("FolderScannerForm_FolderScannerFormFormClosing_Do_you_want_to_cancel_the_scanning" +
                        "_for_new_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconError {
            get {
                object obj = ResourceManager.GetObject("IconError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IconZoom {
            get {
                object obj = ResourceManager.GetObject("IconZoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for missing dependencies.
        /// </summary>
        internal static string PluginsForm_CheckForMissingDependenciesToolStripMenuItemClick_Checking_for_missing_dependencies {
            get {
                return ResourceManager.GetString("PluginsForm_CheckForMissingDependenciesToolStripMenuItemClick_Checking_for_missin" +
                        "g_dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No missing dependencies.
        /// </summary>
        internal static string PluginsForm_DependencyCheckerBackgroundWorkerRunWorkerCompleted_No_missing_dependencies {
            get {
                return ResourceManager.GetString("PluginsForm_DependencyCheckerBackgroundWorkerRunWorkerCompleted_No_missing_depend" +
                        "encies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No missing dependencies were detected..
        /// </summary>
        internal static string PluginsForm_DependencyCheckerBackgroundWorkerRunWorkerCompleted_No_missing_dependencies_were_detected_ {
            get {
                return ResourceManager.GetString("PluginsForm_DependencyCheckerBackgroundWorkerRunWorkerCompleted_No_missing_depend" +
                        "encies_were_detected_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying new plugins.
        /// </summary>
        internal static string PluginsForm_IdentifyNewPluginsToolStripMenuItemClick_Identifying_new_plugins {
            get {
                return ResourceManager.GetString("PluginsForm_IdentifyNewPluginsToolStripMenuItemClick_Identifying_new_plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identified {0} new plugins..
        /// </summary>
        internal static string PluginsForm_IdentifyPluginsBackgroundWorkerRunWorkerCompleted_Identified__0__new_plugins_ {
            get {
                return ResourceManager.GetString("PluginsForm_IdentifyPluginsBackgroundWorkerRunWorkerCompleted_Identified__0__new_" +
                        "plugins_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm cancellation.
        /// </summary>
        internal static string PluginsForm_PluginsFormFormClosing_Confirm_cancellation {
            get {
                return ResourceManager.GetString("PluginsForm_PluginsFormFormClosing_Confirm_cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is still checking for missing dependencies. Close anyway?.
        /// </summary>
        internal static string PluginsForm_PluginsFormFormClosing_The_application_is_still_checking_for_missing_dependencies__Close_anyway_ {
            get {
                return ResourceManager.GetString("PluginsForm_PluginsFormFormClosing_The_application_is_still_checking_for_missing_" +
                        "dependencies__Close_anyway_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is still identifying new plugins. Close anyway?.
        /// </summary>
        internal static string PluginsForm_PluginsFormFormClosing_The_application_is_still_identifying_new_plugins__Close_anyway_ {
            get {
                return ResourceManager.GetString("PluginsForm_PluginsFormFormClosing_The_application_is_still_identifying_new_plugi" +
                        "ns__Close_anyway_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is still updating info for known plugins. Close anyway?.
        /// </summary>
        internal static string PluginsForm_PluginsFormFormClosing_The_application_is_still_updating_info_for_known_plugins__Close_anyway_ {
            get {
                return ResourceManager.GetString("PluginsForm_PluginsFormFormClosing_The_application_is_still_updating_info_for_kno" +
                        "wn_plugins__Close_anyway_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update complete.
        /// </summary>
        internal static string PluginsForm_UpdateInfoBackgroundWorkerRunWorkerCompleted_Update_complete {
            get {
                return ResourceManager.GetString("PluginsForm_UpdateInfoBackgroundWorkerRunWorkerCompleted_Update_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated information for {0} plugins..
        /// </summary>
        internal static string PluginsForm_UpdateInfoBackgroundWorkerRunWorkerCompleted_Updated_information_for__0__plugins_ {
            get {
                return ResourceManager.GetString("PluginsForm_UpdateInfoBackgroundWorkerRunWorkerCompleted_Updated_information_for_" +
                        "_0__plugins_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating info for known plugins from the server..
        /// </summary>
        internal static string PluginsForm_UpdateInfoForKnownPluginsToolStripMenuItemClick_Updating_info_for_known_plugins_from_the_server_ {
            get {
                return ResourceManager.GetString("PluginsForm_UpdateInfoForKnownPluginsToolStripMenuItemClick_Updating_info_for_kno" +
                        "wn_plugins_from_the_server_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is disabled. Go to the settings if you want to enable it..
        /// </summary>
        internal static string This_feature_is_disabled_go_to_the_settings_if_you_want_to_enable_it {
            get {
                return ResourceManager.GetString("This_feature_is_disabled_go_to_the_settings_if_you_want_to_enable_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeView_Folder {
            get {
                object obj = ResourceManager.GetObject("TreeView_Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeView_FolderOpen {
            get {
                object obj = ResourceManager.GetObject("TreeView_FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TreeView_Leaf {
            get {
                object obj = ResourceManager.GetObject("TreeView_Leaf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper1 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper10 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper11 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper12 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper13 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper2 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper3 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper4 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper5 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper6 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper7 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper8 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wallpaper9 {
            get {
                object obj = ResourceManager.GetObject("Wallpaper9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
